version: '3.3'

services:
  mariadb:
    image: mariadb:10.2
    command: --explicit_defaults_for_timestamp=1
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=app_ket
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - "./db/:/var/lib/mysql"